### ISSUE TITLE
Passing --emma-xml tells me that --emma-xml is not a valid switch

### ISSUE THREAD

**Issue by AeroNotix** [JacekLach/cloverage#25]
``` shell

lein cloverage --emma-xml

Exception in thread "main" java.lang.Exception: '--emma-xml' is not a valid argument
    at clojure.tools.cli$apply_specs.invoke(cli.clj:139)
    at clojure.tools.cli$cli.doInvoke(cli.clj:205)
    at clojure.lang.RestFn.invoke(RestFn.java:943)
    at cloverage.coverage$parse_args.invoke(coverage.clj:98)
    at cloverage.coverage$_main.doInvoke(coverage.clj:113)
    at clojure.lang.RestFn.invoke(RestFn.java:3894)
    at clojure.lang.Var.invoke(Var.java:527)
    at user$eval5$fn__7.invoke(form-init6234754591030370870.clj:1)
    at user$eval5.invoke(form-init6234754591030370870.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6619)
    at clojure.lang.Compiler.eval(Compiler.java:6609)
    at clojure.lang.Compiler.load(Compiler.java:7064)
    at clojure.lang.Compiler.loadFile(Compiler.java:7020)
    at clojure.main$load_script.invoke(main.clj:294)
    at clojure.main$init_opt.invoke(main.clj:299)
    at clojure.main$initialize.invoke(main.clj:327)
    at clojure.main$null_opt.invoke(main.clj:362)
    at clojure.main$main.doInvoke(main.clj:440)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:419)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.main.main(main.java:37)

```

**Comment by JacekLach** [comment]
The addition of emma-xml output was... Well, not recent, but hasn't been released yet. I'll probably release `1.0.4`, which will contain this functionality, once lshift/cloverage#28 is fixed.

If you require this functionality right now, you can get it by checking out revision 4887ebeaeecbd0 and installing it locally:

```
git checkout 4887ebeaeecbd0
(cd cloverage && lein install)
CLOVERAGE_VERSION=1.0.4-SNAPSHOT lein cloverage
```

This will give you a version of cloverage that includes EMMA output, but does not suffer from lshift/cloverage#28

Sorry for the hassle involved!

**Comment by AeroNotix** [comment]
(Removed previous comment because wow pgp sigs)

Not a problem! Cheers

**Comment by AeroNotix** [comment]
Unfortunately that still gives me the parse-opts error. Nevermind, I'm just experimenting anyway. Cheers.

**Comment by JacekLach** [comment]
Ooooh, that's good to know. So it's not the commit i thought it was that's breaking the change, it's something about the dependency resolution order when the version of cloverage is 1.0.4-SNAPSHOT rather than 1.0.3. Bizzare, but this will hopefully help me track it down.

**Comment by AeroNotix** [comment]
If you have any more commits/testing ideas, throw 'em my way and I'll be glad to run them.
