### ISSUE TITLE
IllegalArgumentException: Unable to resolve classname: TaskTuple

### ISSUE THREAD

**Issue by wilsonch** [JacekLach/cloverage#26]
When I run lein cloverage with [lein-cloverage "1.0.2"] I'm getting the following exception:

Exception in thread "main" java.lang.IllegalArgumentException: Unable to resolve classname: TaskTuple, compiling:(lamina/time/queue.clj:126:1)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6651)
    at clojure.lang.Compiler.analyze(Compiler.java:6445)
    at clojure.lang.Compiler.analyze(Compiler.java:6406)
    at clojure.lang.Compiler$HostExpr$Parser.parse(Compiler.java:957)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6644)
    at clojure.lang.Compiler.analyze(Compiler.java:6445)
    at clojure.lang.Compiler.analyze(Compiler.java:6406)
    at riddley.Util.localBinding(Util.java:9)
    at riddley.compiler$register_local$fn__587.invoke(compiler.clj:63)
    at clojure.lang.AFn.applyToHelper(AFn.java:152)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.core$apply.invoke(core.clj:624)
    at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1862)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at riddley.compiler$register_local.invoke(compiler.clj:57)
    at riddley.walk$let_bindings$fn__630.invoke(walk.clj:100)
    at clojure.core$map$fn__4245.invoke(core.clj:2559)
    at clojure.lang.LazySeq.sval(LazySeq.java:40)
    at clojure.lang.LazySeq.seq(LazySeq.java:49)
    at clojure.lang.Cons.next(Cons.java:39)
    at clojure.lang.RT.boundedLength(RT.java:1654)
    at clojure.lang.RestFn.applyTo(RestFn.java:130)
    at clojure.core$apply.invoke(core.clj:624)
    at clojure.core$mapcat.doInvoke(core.clj:2586)
    at clojure.lang.RestFn.invoke(RestFn.java:423)
    at riddley.walk$let_bindings.invoke(walk.clj:96)
    at riddley.walk$let_handler$fn__671.invoke(walk.clj:136)

**Comment by JacekLach** [comment]
Probably related to lshift/cloverage#47 (i.e. `potemkin/defrecord+` breaks under cloverage)

**Comment by wilsonch** [comment]
Specifying [riddley "0.1.6"] did not seem to help although the exception is indeed occurring in a defrecord+ containing a let.
